"""
UK plant database: 50+ species with frost dates, seasonal schedules,
planting guidance, and companion planting data.
"""

from datetime import date

UK_REGIONS = {
    "scotland_highlands": {"frost_free_start": (5, 15), "frost_free_end": (9, 15), "name": "Scotland Highlands"},
    "scotland_lowlands":  {"frost_free_start": (4, 20), "frost_free_end": (10, 10), "name": "Scotland Lowlands"},
    "northern_england":   {"frost_free_start": (4, 15), "frost_free_end": (10, 15), "name": "Northern England"},
    "midlands":           {"frost_free_start": (4, 1),  "frost_free_end": (10, 31), "name": "Midlands"},
    "east_anglia":        {"frost_free_start": (3, 25), "frost_free_end": (11, 5),  "name": "East Anglia"},
    "south_east":         {"frost_free_start": (3, 20), "frost_free_end": (11, 10), "name": "South East"},
    "south_west":         {"frost_free_start": (3, 15), "frost_free_end": (11, 20), "name": "South West"},
    "wales":              {"frost_free_start": (4, 5),  "frost_free_end": (10, 25), "name": "Wales"},
    "northern_ireland":   {"frost_free_start": (4, 10), "frost_free_end": (10, 20), "name": "Northern Ireland"},
}

POSTCODE_TO_REGION = {
    "AB": "scotland_highlands", "DD": "scotland_lowlands", "DG": "scotland_lowlands",
    "EH": "scotland_lowlands",  "FK": "scotland_lowlands",  "G":  "scotland_lowlands",
    "HS": "scotland_highlands", "IV": "scotland_highlands", "KA": "scotland_lowlands",
    "KW": "scotland_highlands", "KY": "scotland_lowlands",  "ML": "scotland_lowlands",
    "PA": "scotland_lowlands",  "PH": "scotland_highlands", "TD": "scotland_lowlands",
    "ZE": "scotland_highlands",
    "BT": "northern_ireland",
    "CA": "northern_england",   "DL": "northern_england",   "HD": "northern_england",
    "HG": "northern_england",   "HU": "northern_england",   "HX": "northern_england",
    "LA": "northern_england",   "LS": "northern_england",   "NE": "northern_england",
    "SR": "northern_england",   "TS": "northern_england",   "WF": "northern_england",
    "YO": "northern_england",
    "CH": "midlands",           "CW": "midlands",           "DE": "midlands",
    "DY": "midlands",           "LE": "midlands",           "NG": "midlands",
    "ST": "midlands",           "WS": "midlands",           "WV": "midlands",
    "B":  "midlands",           "CV": "midlands",
    "CB": "east_anglia",        "CO": "east_anglia",        "IP": "east_anglia",
    "NR": "east_anglia",        "PE": "east_anglia",
    "BN": "south_east",         "BR": "south_east",         "CT": "south_east",
    "DA": "south_east",         "GU": "south_east",         "KT": "south_east",
    "ME": "south_east",         "MK": "south_east",         "OX": "south_east",
    "PO": "south_east",         "RG": "south_east",         "RH": "south_east",
    "SE": "south_east",         "SL": "south_east",         "SM": "south_east",
    "SO": "south_east",         "SW": "south_east",         "TN": "south_east",
    "TW": "south_east",         "W":  "south_east",         "WC": "south_east",
    "BS": "south_west",         "BA": "south_west",         "DT": "south_west",
    "EX": "south_west",         "GL": "south_west",         "PL": "south_west",
    "SP": "south_west",         "TA": "south_west",         "TQ": "south_west",
    "TR": "south_west",
    "CF": "wales",              "LD": "wales",              "LL": "wales",
    "NP": "wales",              "SA": "wales",              "SY": "wales",
}

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

PLANTS = [
    {
        "id": "tomato",
        "common_name": "Tomato",
        "latin_name": "Solanum lycopersicum",
        "category": "vegetable",
        "emoji": "🍅",
        "description": "Popular greenhouse and outdoor fruit-vegetable. Needs warmth and sun.",
        "difficulty": "moderate",
        "sow_indoors": [2, 3, 4],
        "sow_outdoors": [],
        "transplant": [5, 6],
        "harvest": [7, 8, 9, 10],
        "prune": [6, 7, 8],
        "prune_notes": "Remove side shoots (suckers) for cordon varieties. Pinch out growing tip at 4-6 trusses.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "rich, well-drained",
        "spacing_cm": 45,
        "height_cm": 120,
        "frost_tender": True,
        "companions": ["basil", "carrot", "parsley"],
        "avoid": ["fennel", "brassica"],
        "pests": ["aphids", "whitefly", "blight"],
        "tips": "Feed weekly with high-potash fertiliser once flowering.",
    },
    {
        "id": "courgette",
        "common_name": "Courgette",
        "latin_name": "Cucurbita pepo",
        "category": "vegetable",
        "emoji": "🥒",
        "description": "Prolific summer squash. One plant produces abundantly.",
        "difficulty": "easy",
        "sow_indoors": [4, 5],
        "sow_outdoors": [5, 6],
        "transplant": [5, 6],
        "harvest": [6, 7, 8, 9],
        "prune": [],
        "prune_notes": "No pruning needed. Remove dying leaves to improve airflow.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "rich, moisture-retentive",
        "spacing_cm": 90,
        "height_cm": 60,
        "frost_tender": True,
        "companions": ["nasturtium", "marigold"],
        "avoid": [],
        "pests": ["powdery_mildew", "aphids"],
        "tips": "Harvest when 15–20 cm long for best flavour.",
    },
    {
        "id": "runner_bean",
        "common_name": "Runner Bean",
        "latin_name": "Phaseolus coccineus",
        "category": "vegetable",
        "emoji": "🫘",
        "description": "British garden staple. Bright red flowers, prolific pods.",
        "difficulty": "easy",
        "sow_indoors": [4, 5],
        "sow_outdoors": [5, 6],
        "transplant": [5, 6],
        "harvest": [7, 8, 9, 10],
        "prune": [8],
        "prune_notes": "Pinch out growing tips when plants reach top of supports.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "rich, well-drained",
        "spacing_cm": 25,
        "height_cm": 200,
        "frost_tender": True,
        "companions": ["sweetcorn", "carrot", "cucumber"],
        "avoid": ["fennel", "onion"],
        "pests": ["slugs", "aphids", "bean_weevil"],
        "tips": "Soak seeds overnight before sowing. Keep picking to extend harvest.",
    },
    {
        "id": "potato",
        "common_name": "Potato",
        "latin_name": "Solanum tuberosum",
        "category": "vegetable",
        "emoji": "🥔",
        "description": "UK staple crop. Easties and maincrops suit different seasons.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [3, 4, 5],
        "transplant": [],
        "harvest": [6, 7, 8, 9, 10],
        "prune": [],
        "prune_notes": "Earth up stems as they grow to prevent greening.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "loose, fertile",
        "spacing_cm": 30,
        "height_cm": 60,
        "frost_tender": True,
        "companions": ["horseradish", "marigold", "beans"],
        "avoid": ["tomato", "squash"],
        "pests": ["blight", "slugs", "wireworm"],
        "tips": "Chit seed potatoes (leave in light to sprout) for 4–6 weeks before planting.",
    },
    {
        "id": "carrot",
        "common_name": "Carrot",
        "latin_name": "Daucus carota subsp. sativus",
        "category": "vegetable",
        "emoji": "🥕",
        "description": "Sweet root vegetable. Avoid freshly manured soil.",
        "difficulty": "moderate",
        "sow_indoors": [],
        "sow_outdoors": [3, 4, 5, 6, 7],
        "transplant": [],
        "harvest": [6, 7, 8, 9, 10, 11],
        "prune": [],
        "prune_notes": "Thin seedlings to 5 cm apart when 2 cm tall.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "sandy, stone-free, well-drained",
        "spacing_cm": 5,
        "height_cm": 30,
        "frost_tender": False,
        "companions": ["rosemary", "sage", "leek", "onion"],
        "avoid": ["dill"],
        "pests": ["carrot_fly", "slugs"],
        "tips": "Cover with fleece to deter carrot fly. Sow thinly to reduce thinning.",
    },
    {
        "id": "onion",
        "common_name": "Onion",
        "latin_name": "Allium cepa",
        "category": "vegetable",
        "emoji": "🧅",
        "description": "Essential kitchen crop. Sets are easier than seed for beginners.",
        "difficulty": "easy",
        "sow_indoors": [1, 2],
        "sow_outdoors": [3, 4],
        "transplant": [4, 5],
        "harvest": [7, 8, 9],
        "prune": [],
        "prune_notes": "Bend over leaves in July to encourage bulbing and ripening.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "firm, fertile, well-drained",
        "spacing_cm": 10,
        "height_cm": 30,
        "frost_tender": False,
        "companions": ["carrot", "tomato", "chamomile"],
        "avoid": ["bean", "pea"],
        "pests": ["onion_fly", "white_rot"],
        "tips": "Plant sets in autumn for an earlier crop next year.",
    },
    {
        "id": "garlic",
        "common_name": "Garlic",
        "latin_name": "Allium sativum",
        "category": "vegetable",
        "emoji": "🧄",
        "description": "Plant in autumn for a summer harvest. UK hardneck varieties recommended.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [10, 11, 2, 3],
        "transplant": [],
        "harvest": [6, 7],
        "prune": [5, 6],
        "prune_notes": "Remove scapes (flower stalks) on hardneck varieties to direct energy to bulbs.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained, fertile",
        "spacing_cm": 15,
        "height_cm": 40,
        "frost_tender": False,
        "companions": ["rose", "tomato", "carrot"],
        "avoid": ["bean", "pea"],
        "pests": ["rust", "white_rot"],
        "tips": "Break bulbs into cloves just before planting. Point upward, 5 cm deep.",
    },
    {
        "id": "broad_bean",
        "common_name": "Broad Bean",
        "latin_name": "Vicia faba",
        "category": "vegetable",
        "emoji": "🫘",
        "description": "Hardy British favourite. Can be sown in autumn for early crops.",
        "difficulty": "easy",
        "sow_indoors": [2, 3],
        "sow_outdoors": [11, 2, 3, 4],
        "transplant": [3, 4],
        "harvest": [5, 6, 7],
        "prune": [4, 5],
        "prune_notes": "Pinch out growing tips once 4–6 pods set. Deters blackfly.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "well-drained, fertile",
        "spacing_cm": 22,
        "height_cm": 90,
        "frost_tender": False,
        "companions": ["carrot", "potato", "spinach"],
        "avoid": ["onion", "garlic"],
        "pests": ["blackfly", "chocolate_spot"],
        "tips": "Autumn-sown plants are more resistant to blackfly.",
    },
    {
        "id": "pea",
        "common_name": "Garden Pea",
        "latin_name": "Pisum sativum",
        "category": "vegetable",
        "emoji": "🫛",
        "description": "Sweet pods taste best fresh from the garden. Provide support.",
        "difficulty": "easy",
        "sow_indoors": [2, 3],
        "sow_outdoors": [3, 4, 5, 6],
        "transplant": [4, 5],
        "harvest": [6, 7, 8],
        "prune": [],
        "prune_notes": "Provide twiggy sticks or netting for support.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "well-drained, fertile",
        "spacing_cm": 8,
        "height_cm": 75,
        "frost_tender": False,
        "companions": ["bean", "carrot", "spinach"],
        "avoid": ["onion", "garlic"],
        "pests": ["pea_moth", "birds", "powdery_mildew"],
        "tips": "Sow successionally every 2–3 weeks for a longer harvest.",
    },
    {
        "id": "lettuce",
        "common_name": "Lettuce",
        "latin_name": "Lactuca sativa",
        "category": "vegetable",
        "emoji": "🥬",
        "description": "Fast-growing salad crop. Cut-and-come-again varieties give weeks of leaves.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [3, 4, 5, 6, 7, 8],
        "transplant": [4, 5],
        "harvest": [5, 6, 7, 8, 9, 10],
        "prune": [],
        "prune_notes": "Harvest outer leaves or cut 2 cm above base for regrowth.",
        "watering": "moderate",
        "sunlight": "partial_shade",
        "soil": "moisture-retentive, fertile",
        "spacing_cm": 25,
        "height_cm": 20,
        "frost_tender": False,
        "companions": ["carrot", "radish", "strawberry"],
        "avoid": ["celery"],
        "pests": ["slugs", "aphids", "downy_mildew"],
        "tips": "Sow little and often. Afternoon shade prevents bolting in summer.",
    },
    {
        "id": "kale",
        "common_name": "Kale",
        "latin_name": "Brassica oleracea var. sabellica",
        "category": "vegetable",
        "emoji": "🥦",
        "description": "Hardy winter green. Improves in flavour after frost.",
        "difficulty": "easy",
        "sow_indoors": [4, 5],
        "sow_outdoors": [5, 6],
        "transplant": [6, 7],
        "harvest": [10, 11, 12, 1, 2, 3],
        "prune": [],
        "prune_notes": "Remove lower yellowing leaves. Harvest young leaves from top.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, firm",
        "spacing_cm": 45,
        "height_cm": 75,
        "frost_tender": False,
        "companions": ["celery", "potato", "dill"],
        "avoid": ["tomato", "strawberry"],
        "pests": ["cabbage_white", "aphids", "clubroot"],
        "tips": "Net against cabbage white butterflies. Firm soil after planting.",
    },
    {
        "id": "leek",
        "common_name": "Leek",
        "latin_name": "Allium ampeloprasum",
        "category": "vegetable",
        "emoji": "🌿",
        "description": "Mild allium, perfect for winter harvests. Classic allotment crop.",
        "difficulty": "moderate",
        "sow_indoors": [2, 3],
        "sow_outdoors": [3, 4],
        "transplant": [6, 7],
        "harvest": [10, 11, 12, 1, 2, 3],
        "prune": [],
        "prune_notes": "Earth up stems as they grow to blanch and extend white part.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, well-drained",
        "spacing_cm": 15,
        "height_cm": 45,
        "frost_tender": False,
        "companions": ["carrot", "celery", "onion"],
        "avoid": ["bean", "pea"],
        "pests": ["leek_rust", "onion_fly"],
        "tips": "Drop transplants into 15 cm holes; don't fill — just water in.",
    },
    {
        "id": "beetroot",
        "common_name": "Beetroot",
        "latin_name": "Beta vulgaris",
        "category": "vegetable",
        "emoji": "🫚",
        "description": "Colourful root with edible leaves. Easy and reliable.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [4, 5, 6, 7],
        "transplant": [],
        "harvest": [6, 7, 8, 9, 10],
        "prune": [],
        "prune_notes": "Thin to 10 cm spacing. Thinnings are edible.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "well-drained, not recently limed",
        "spacing_cm": 10,
        "height_cm": 30,
        "frost_tender": False,
        "companions": ["onion", "lettuce", "cabbage"],
        "avoid": ["bean", "mustard"],
        "pests": ["leaf_miner", "birds"],
        "tips": "Soak 'seeds' (corky clusters) for 1 hour before sowing.",
    },
    {
        "id": "spinach",
        "common_name": "Spinach",
        "latin_name": "Spinacia oleracea",
        "category": "vegetable",
        "emoji": "🥬",
        "description": "Fast-cropping leaf vegetable, rich in iron. Bolts in heat.",
        "difficulty": "moderate",
        "sow_indoors": [],
        "sow_outdoors": [3, 4, 5, 8, 9],
        "transplant": [],
        "harvest": [4, 5, 6, 9, 10, 11],
        "prune": [],
        "prune_notes": "Pick outer leaves regularly to encourage new growth.",
        "watering": "regular",
        "sunlight": "partial_shade",
        "soil": "nitrogen-rich, moisture-retentive",
        "spacing_cm": 15,
        "height_cm": 20,
        "frost_tender": False,
        "companions": ["pea", "celery", "strawberry"],
        "avoid": [],
        "pests": ["downy_mildew", "slugs"],
        "tips": "Avoid summer sowing — use perpetual spinach instead.",
    },
    {
        "id": "cucumber",
        "common_name": "Cucumber",
        "latin_name": "Cucumis sativus",
        "category": "vegetable",
        "emoji": "🥒",
        "description": "Greenhouse or outdoor ridge types. Needs warmth.",
        "difficulty": "moderate",
        "sow_indoors": [4, 5],
        "sow_outdoors": [],
        "transplant": [5, 6],
        "harvest": [7, 8, 9],
        "prune": [6, 7, 8],
        "prune_notes": "Pinch out growing tip after 6 leaves. Remove side shoots beyond 2 leaves.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "rich, warm, moisture-retentive",
        "spacing_cm": 45,
        "height_cm": 150,
        "frost_tender": True,
        "companions": ["bean", "pea", "sunflower"],
        "avoid": ["potato", "sage"],
        "pests": ["red_spider_mite", "powdery_mildew"],
        "tips": "For greenhouse types, remove male flowers to prevent bitterness.",
    },
    {
        "id": "cabbage",
        "common_name": "Cabbage",
        "latin_name": "Brassica oleracea var. capitata",
        "category": "vegetable",
        "emoji": "🥬",
        "description": "Reliable brassica for all seasons. Firm soil well after planting.",
        "difficulty": "moderate",
        "sow_indoors": [3, 4, 6, 7],
        "sow_outdoors": [4, 5],
        "transplant": [5, 6, 7, 8],
        "harvest": [7, 8, 9, 10, 11, 12, 1, 2],
        "prune": [],
        "prune_notes": "Remove outer yellowing leaves. Net against butterflies.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "firm, fertile, limed if acid",
        "spacing_cm": 45,
        "height_cm": 40,
        "frost_tender": False,
        "companions": ["celery", "potato", "dill"],
        "avoid": ["tomato", "strawberry"],
        "pests": ["cabbage_white", "clubroot", "slugs"],
        "tips": "Club root is soil-borne; avoid planting brassicas in same spot more than once every 4 years.",
    },
    {
        "id": "broccoli",
        "common_name": "Purple Sprouting Broccoli",
        "latin_name": "Brassica oleracea var. italica",
        "category": "vegetable",
        "emoji": "🥦",
        "description": "UK winter staple. Purple spears harvested Feb–Apr when little else is available.",
        "difficulty": "moderate",
        "sow_indoors": [4, 5],
        "sow_outdoors": [5, 6],
        "transplant": [6, 7],
        "harvest": [2, 3, 4],
        "prune": [],
        "prune_notes": "Harvest central head first, then side shoots. Don't let it flower.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "firm, fertile",
        "spacing_cm": 60,
        "height_cm": 90,
        "frost_tender": False,
        "companions": ["celery", "potato", "onion"],
        "avoid": ["tomato"],
        "pests": ["cabbage_white", "pigeons", "clubroot"],
        "tips": "Stake tall plants against winter winds.",
    },
    {
        "id": "parsnip",
        "common_name": "Parsnip",
        "latin_name": "Pastinaca sativa",
        "category": "vegetable",
        "emoji": "🫚",
        "description": "Long-season UK root veg. Improved by autumn frosts.",
        "difficulty": "moderate",
        "sow_indoors": [],
        "sow_outdoors": [3, 4, 5],
        "transplant": [],
        "harvest": [10, 11, 12, 1, 2, 3],
        "prune": [],
        "prune_notes": "No pruning needed. Leave in ground and harvest as needed.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "deep, stone-free",
        "spacing_cm": 15,
        "height_cm": 30,
        "frost_tender": False,
        "companions": ["pea", "potato", "garlic"],
        "avoid": ["carrot"],
        "pests": ["carrot_fly", "parsnip_canker"],
        "tips": "Fresh seed each year — germination drops sharply after one year.",
    },
    {
        "id": "sweetcorn",
        "common_name": "Sweetcorn",
        "latin_name": "Zea mays",
        "category": "vegetable",
        "emoji": "🌽",
        "description": "Plant in blocks for wind pollination. Eat within hours of picking.",
        "difficulty": "moderate",
        "sow_indoors": [4, 5],
        "sow_outdoors": [5],
        "transplant": [5, 6],
        "harvest": [8, 9],
        "prune": [],
        "prune_notes": "Remove side tillers to concentrate energy in main stems.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "rich, warm, well-drained",
        "spacing_cm": 45,
        "height_cm": 180,
        "frost_tender": True,
        "companions": ["bean", "squash", "courgette"],
        "avoid": [],
        "pests": ["birds", "squirrels"],
        "tips": "Test readiness by piercing a kernel — milky juice means ready.",
    },
    {
        "id": "strawberry",
        "common_name": "Strawberry",
        "latin_name": "Fragaria × ananassa",
        "category": "fruit",
        "emoji": "🍓",
        "description": "British summer favourite. Plants fruit for 3–4 years.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [8, 9, 3, 4],
        "transplant": [8, 9],
        "harvest": [6, 7, 8],
        "prune": [8, 9],
        "prune_notes": "After harvest, cut back old foliage to 10 cm. Remove runners unless propagating.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "well-drained, slightly acid",
        "spacing_cm": 35,
        "height_cm": 20,
        "frost_tender": False,
        "companions": ["borage", "lettuce", "spinach"],
        "avoid": ["brassica", "fennel"],
        "pests": ["slugs", "vine_weevil", "grey_mould"],
        "tips": "Use straw under fruit to keep clean and retain moisture.",
    },
    {
        "id": "raspberry",
        "common_name": "Raspberry",
        "latin_name": "Rubus idaeus",
        "category": "fruit",
        "emoji": "🫐",
        "description": "Summer or autumn varieties. One of the most popular UK soft fruits.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [11, 12, 1, 2, 3],
        "transplant": [],
        "harvest": [6, 7, 8, 9, 10],
        "prune": [2, 3, 9, 10],
        "prune_notes": "Summer varieties: cut fruited canes to ground after harvest, tie in new canes. Autumn: cut all canes to ground in Feb.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "slightly acid, well-drained, fertile",
        "spacing_cm": 45,
        "height_cm": 150,
        "frost_tender": False,
        "companions": ["garlic", "rue"],
        "avoid": ["potato", "tomato"],
        "pests": ["raspberry_beetle", "spur_blight", "grey_mould"],
        "tips": "Tie canes to wires at 60 cm and 120 cm for support.",
    },
    {
        "id": "apple",
        "common_name": "Apple",
        "latin_name": "Malus domestica",
        "category": "fruit",
        "emoji": "🍎",
        "description": "Britain's most popular tree fruit. Needs pollination partner.",
        "difficulty": "moderate",
        "sow_indoors": [],
        "sow_outdoors": [11, 12, 1, 2, 3],
        "transplant": [],
        "harvest": [8, 9, 10, 11],
        "prune": [12, 1, 2],
        "prune_notes": "Winter prune to open up the crown. Remove dead, diseased, and crossing branches. Summer prune (Aug) sideshoots to 5 leaves on trained forms.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "deep, well-drained",
        "spacing_cm": 400,
        "height_cm": 350,
        "frost_tender": False,
        "companions": ["chive", "nasturtium", "foxglove"],
        "avoid": [],
        "pests": ["codling_moth", "scab", "woolly_aphid"],
        "tips": "Choose a pollination group matching a nearby variety or crab apple.",
    },
    {
        "id": "blackcurrant",
        "common_name": "Blackcurrant",
        "latin_name": "Ribes nigrum",
        "category": "fruit",
        "emoji": "🫐",
        "description": "Hardy British soft fruit. High in vitamin C. Tolerates partial shade.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [10, 11, 3],
        "transplant": [],
        "harvest": [7, 8],
        "prune": [10, 11],
        "prune_notes": "Cut out 1/3 of oldest (darkest) stems to ground after harvest.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, moisture-retentive",
        "spacing_cm": 150,
        "height_cm": 150,
        "frost_tender": False,
        "companions": ["garlic", "hyssop"],
        "avoid": [],
        "pests": ["big_bud_mite", "reversion_disease"],
        "tips": "Plant 5 cm deeper than the nursery mark to encourage new shoots.",
    },
    {
        "id": "rose",
        "common_name": "Rose",
        "latin_name": "Rosa",
        "category": "flower",
        "emoji": "🌹",
        "description": "Classic British garden plant. Huge variety of forms and colours.",
        "difficulty": "moderate",
        "sow_indoors": [],
        "sow_outdoors": [11, 12, 1, 2, 3],
        "transplant": [],
        "harvest": [],
        "prune": [3, 10],
        "prune_notes": "Hybrid teas/floribundas: hard prune to outward-facing bud at 30 cm in March. Shrub roses: light tidy, remove 1/3 oldest stems. Climbers: reduce sideshoots to 3 buds after flowering.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, well-drained, slightly acid",
        "spacing_cm": 60,
        "height_cm": 120,
        "frost_tender": False,
        "companions": ["lavender", "allium", "catmint"],
        "avoid": ["brassica"],
        "pests": ["aphids", "blackspot", "powdery_mildew", "rust"],
        "tips": "Deadhead regularly for repeat-flowering varieties. Mulch in spring.",
    },
    {
        "id": "lavender",
        "common_name": "Lavender",
        "latin_name": "Lavandula angustifolia",
        "category": "herb",
        "emoji": "💜",
        "description": "Fragrant UK garden classic. Attracts pollinators and deters pests.",
        "difficulty": "easy",
        "sow_indoors": [2, 3, 4],
        "sow_outdoors": [5, 6],
        "transplant": [5, 6],
        "harvest": [6, 7, 8],
        "prune": [8, 9, 3],
        "prune_notes": "Trim lightly after flowering (Aug/Sep) removing spent flower stems. Light tidy in March. Never cut into old wood.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained, alkaline preferred",
        "spacing_cm": 45,
        "height_cm": 60,
        "frost_tender": False,
        "companions": ["rose", "sage", "carrot"],
        "avoid": [],
        "pests": ["rosemary_beetle"],
        "tips": "Excellent on chalk or sandy soils. Hates wet, heavy clay.",
    },
    {
        "id": "basil",
        "common_name": "Basil",
        "latin_name": "Ocimum basilicum",
        "category": "herb",
        "emoji": "🌿",
        "description": "Aromatic Mediterranean herb. Needs warmth and shelter in UK.",
        "difficulty": "moderate",
        "sow_indoors": [3, 4, 5],
        "sow_outdoors": [],
        "transplant": [5, 6],
        "harvest": [6, 7, 8, 9],
        "prune": [6, 7, 8, 9],
        "prune_notes": "Regularly pinch out flower buds and stem tips to promote bushy growth.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "rich, well-drained, warm",
        "spacing_cm": 20,
        "height_cm": 40,
        "frost_tender": True,
        "companions": ["tomato", "pepper", "asparagus"],
        "avoid": ["sage"],
        "pests": ["aphids", "slugs"],
        "tips": "Keep on a warm windowsill until nights are reliably above 10°C.",
    },
    {
        "id": "mint",
        "common_name": "Mint",
        "latin_name": "Mentha",
        "category": "herb",
        "emoji": "🌿",
        "description": "Vigorous and aromatic. Grow in containers to prevent spreading.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [4, 5],
        "transplant": [4, 5],
        "harvest": [5, 6, 7, 8, 9],
        "prune": [8, 9],
        "prune_notes": "Cut back hard in late summer to encourage fresh, vigorous growth.",
        "watering": "moderate",
        "sunlight": "partial_shade",
        "soil": "moisture-retentive",
        "spacing_cm": 30,
        "height_cm": 60,
        "frost_tender": False,
        "companions": ["cabbage", "tomato", "pea"],
        "avoid": [],
        "pests": ["mint_beetle", "rust"],
        "tips": "Sink pots in the ground to limit spread. Replant every 2–3 years.",
    },
    {
        "id": "rosemary",
        "common_name": "Rosemary",
        "latin_name": "Salvia rosmarinus",
        "category": "herb",
        "emoji": "🌿",
        "description": "Evergreen aromatic shrub. Hardy in most UK regions.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [5, 6],
        "transplant": [5, 6],
        "harvest": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "prune": [4, 5, 9],
        "prune_notes": "Trim lightly after flowering in April/May. Don't cut into old wood.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained, poor to moderate",
        "spacing_cm": 50,
        "height_cm": 100,
        "frost_tender": False,
        "companions": ["carrot", "bean", "sage"],
        "avoid": [],
        "pests": ["rosemary_beetle"],
        "tips": "Excellent in poor, dry soils. Sheltered from harsh north winds.",
    },
    {
        "id": "chive",
        "common_name": "Chive",
        "latin_name": "Allium schoenoprasum",
        "category": "herb",
        "emoji": "🌿",
        "description": "Hardy perennial onion relative. Flowers attract pollinators.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [4, 5],
        "transplant": [4, 5],
        "harvest": [3, 4, 5, 6, 7, 8, 9, 10],
        "prune": [6, 7],
        "prune_notes": "Cut flower heads before seeds form, or deadhead after flowering.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, well-drained",
        "spacing_cm": 20,
        "height_cm": 30,
        "frost_tender": False,
        "companions": ["carrot", "apple", "rose"],
        "avoid": ["bean", "pea"],
        "pests": ["onion_fly"],
        "tips": "Divide clumps every 3 years for best results.",
    },
    {
        "id": "sunflower",
        "common_name": "Sunflower",
        "latin_name": "Helianthus annuus",
        "category": "flower",
        "emoji": "🌻",
        "description": "Cheerful annual. Excellent for wildlife and children's gardens.",
        "difficulty": "easy",
        "sow_indoors": [4, 5],
        "sow_outdoors": [5, 6],
        "transplant": [5, 6],
        "harvest": [9, 10],
        "prune": [],
        "prune_notes": "Deadhead smaller varieties for prolonged flowering.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "well-drained",
        "spacing_cm": 30,
        "height_cm": 200,
        "frost_tender": True,
        "companions": ["cucumber", "squash"],
        "avoid": ["potato"],
        "pests": ["slugs", "birds"],
        "tips": "Tall varieties may need staking.",
    },
    {
        "id": "sweet_pea",
        "common_name": "Sweet Pea",
        "latin_name": "Lathyrus odoratus",
        "category": "flower",
        "emoji": "🌸",
        "description": "Fragrant climbing annual. British garden institution.",
        "difficulty": "easy",
        "sow_indoors": [11, 1, 2, 3],
        "sow_outdoors": [4, 10, 11],
        "transplant": [4, 5],
        "harvest": [6, 7, 8, 9],
        "prune": [5, 6, 7, 8],
        "prune_notes": "Deadhead or cut regularly — leaving seeds stops flowering.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, deeply dug",
        "spacing_cm": 20,
        "height_cm": 200,
        "frost_tender": False,
        "companions": ["carrot", "radish"],
        "avoid": [],
        "pests": ["aphids", "slugs"],
        "tips": "Nick or soak seeds before sowing. Autumn-sown plants are more vigorous.",
    },
    {
        "id": "dahlia",
        "common_name": "Dahlia",
        "latin_name": "Dahlia",
        "category": "flower",
        "emoji": "🌸",
        "description": "Spectacular late-summer blooms. Tubers must be lifted in UK winters.",
        "difficulty": "moderate",
        "sow_indoors": [3, 4],
        "sow_outdoors": [],
        "transplant": [5, 6],
        "harvest": [],
        "prune": [6, 7, 8, 9],
        "prune_notes": "Deadhead regularly. Disbud for larger blooms. Pinch out growing tip for bushy plants.",
        "watering": "regular",
        "sunlight": "full_sun",
        "soil": "fertile, well-drained",
        "spacing_cm": 60,
        "height_cm": 120,
        "frost_tender": True,
        "companions": ["zinnia", "cosmos"],
        "avoid": [],
        "pests": ["earwigs", "aphids", "slugs"],
        "tips": "Lift tubers after first frost, dry, and store in frost-free shed over winter.",
    },
    {
        "id": "marigold",
        "common_name": "Marigold (French)",
        "latin_name": "Tagetes patula",
        "category": "flower",
        "emoji": "🌼",
        "description": "Companion-planting powerhouse. Deters whitefly and attracts beneficial insects.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [5, 6],
        "transplant": [5, 6],
        "harvest": [],
        "prune": [6, 7, 8, 9],
        "prune_notes": "Deadhead to maintain prolific flowering through summer.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "any well-drained",
        "spacing_cm": 20,
        "height_cm": 30,
        "frost_tender": True,
        "companions": ["tomato", "courgette", "bean"],
        "avoid": [],
        "pests": [],
        "tips": "Plant around vegetable beds as a living pest barrier.",
    },
    {
        "id": "nasturtium",
        "common_name": "Nasturtium",
        "latin_name": "Tropaeolum majus",
        "category": "flower",
        "emoji": "🌼",
        "description": "Edible flowers and leaves. Sacrificial crop for aphids.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [5, 6],
        "transplant": [],
        "harvest": [6, 7, 8, 9],
        "prune": [],
        "prune_notes": "No pruning needed. Self-seeds freely.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "poor to moderate, well-drained",
        "spacing_cm": 30,
        "height_cm": 40,
        "frost_tender": True,
        "companions": ["courgette", "cucumber", "tomato"],
        "avoid": [],
        "pests": ["blackfly", "cabbage_white"],
        "tips": "Rich soil produces foliage at the expense of flowers.",
    },
    {
        "id": "foxglove",
        "common_name": "Foxglove",
        "latin_name": "Digitalis purpurea",
        "category": "flower",
        "emoji": "🌸",
        "description": "Stunning native biennial. Excellent for bees and wildlife gardens.",
        "difficulty": "easy",
        "sow_indoors": [5, 6],
        "sow_outdoors": [5, 6, 7],
        "transplant": [9, 10],
        "harvest": [],
        "prune": [7, 8],
        "prune_notes": "Cut central spike after flowering to encourage lateral spikes. Allow some seed heads for self-seeding.",
        "watering": "moderate",
        "sunlight": "partial_shade",
        "soil": "acidic, well-drained",
        "spacing_cm": 45,
        "height_cm": 120,
        "frost_tender": False,
        "companions": ["apple", "potato"],
        "avoid": [],
        "pests": [],
        "tips": "All parts are toxic. Biennial — flowers in its second year.",
    },
    {
        "id": "buddleja",
        "common_name": "Buddleja",
        "latin_name": "Buddleja davidii",
        "category": "shrub",
        "emoji": "🌿",
        "description": "Butterfly bush. Vigorous summer-flowering shrub.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [10, 3],
        "transplant": [],
        "harvest": [],
        "prune": [3, 4],
        "prune_notes": "Cut back hard to a permanent framework of 50–60 cm in March. Remove spent flower spikes in summer to encourage more blooms.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained",
        "spacing_cm": 200,
        "height_cm": 250,
        "frost_tender": False,
        "companions": [],
        "avoid": [],
        "pests": ["capsid_bug"],
        "tips": "Listed as invasive in some areas — deadhead to prevent spread.",
    },
    {
        "id": "hydrangea",
        "common_name": "Hydrangea",
        "latin_name": "Hydrangea macrophylla",
        "category": "shrub",
        "emoji": "💐",
        "description": "Classic garden shrub. Flower colour depends on soil pH.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [10, 11, 3, 4],
        "transplant": [],
        "harvest": [],
        "prune": [3, 4],
        "prune_notes": "Mophead/lacecap: remove only old flower heads and dead wood in March. Don't cut back hard — flowers form on previous year's wood.",
        "watering": "regular",
        "sunlight": "partial_shade",
        "soil": "moisture-retentive, rich",
        "spacing_cm": 150,
        "height_cm": 150,
        "frost_tender": False,
        "companions": [],
        "avoid": [],
        "pests": ["vine_weevil", "honey_fungus"],
        "tips": "Add iron sulphate for blue flowers on acid soil; lime for pink.",
    },
    {
        "id": "clematis",
        "common_name": "Clematis",
        "latin_name": "Clematis",
        "category": "climber",
        "emoji": "🌸",
        "description": "Versatile flowering climber. Pruning group depends on variety.",
        "difficulty": "moderate",
        "sow_indoors": [],
        "sow_outdoors": [10, 11, 3, 4],
        "transplant": [],
        "harvest": [],
        "prune": [2, 3],
        "prune_notes": "Group 1 (spring): no pruning. Group 2 (early summer): light prune in Feb. Group 3 (late summer): cut to 30 cm in Feb.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, well-drained",
        "spacing_cm": 100,
        "height_cm": 400,
        "frost_tender": False,
        "companions": ["rose", "wisteria"],
        "avoid": [],
        "pests": ["clematis_wilt", "aphids"],
        "tips": "Plant 15 cm deeper than pot depth to protect against clematis wilt.",
    },
    {
        "id": "wisteria",
        "common_name": "Wisteria",
        "latin_name": "Wisteria sinensis",
        "category": "climber",
        "emoji": "💜",
        "description": "Spectacular flowering climber. Can take years to bloom from seed.",
        "difficulty": "hard",
        "sow_indoors": [],
        "sow_outdoors": [10, 11, 3],
        "transplant": [],
        "harvest": [],
        "prune": [2, 8],
        "prune_notes": "TWICE a year is essential. August: cut sideshoots to 5 leaves. February: cut same shoots back to 2–3 buds.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "fertile, well-drained",
        "spacing_cm": 500,
        "height_cm": 1000,
        "frost_tender": False,
        "companions": [],
        "avoid": [],
        "pests": ["scale_insect", "aphids"],
        "tips": "Buy grafted plants for quicker flowering. Provide very strong support.",
    },
    {
        "id": "hosta",
        "common_name": "Hosta",
        "latin_name": "Hosta",
        "category": "perennial",
        "emoji": "🌿",
        "description": "Shade-tolerant perennial grown for dramatic foliage.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [3, 4, 9, 10],
        "transplant": [],
        "harvest": [],
        "prune": [10, 11],
        "prune_notes": "Cut back leaves to ground when they die down in autumn.",
        "watering": "regular",
        "sunlight": "full_shade",
        "soil": "moisture-retentive, humus-rich",
        "spacing_cm": 60,
        "height_cm": 60,
        "frost_tender": False,
        "companions": ["fern", "astilbe"],
        "avoid": [],
        "pests": ["slugs", "vine_weevil"],
        "tips": "Protect emerging shoots with copper tape or beer traps against slugs.",
    },
    {
        "id": "fuchsia",
        "common_name": "Fuchsia",
        "latin_name": "Fuchsia",
        "category": "shrub",
        "emoji": "🌺",
        "description": "Long-flowering tender/hardy shrub. Ideal for containers and baskets.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [],
        "transplant": [5, 6],
        "harvest": [],
        "prune": [4, 5],
        "prune_notes": "Hardy fuchsias: cut back to 15 cm in April when new growth shows. Tender types: prune under glass.",
        "watering": "regular",
        "sunlight": "partial_shade",
        "soil": "fertile, well-drained",
        "spacing_cm": 45,
        "height_cm": 90,
        "frost_tender": True,
        "companions": [],
        "avoid": [],
        "pests": ["fuchsia_gall_mite", "vine_weevil", "aphids"],
        "tips": "Hardy varieties survive UK winters if mulched. Tender types must be overwintered frost-free.",
    },
    {
        "id": "geranium",
        "common_name": "Hardy Geranium (Cranesbill)",
        "latin_name": "Geranium",
        "category": "perennial",
        "emoji": "🌸",
        "description": "Ground-covering perennial. Extremely versatile UK garden plant.",
        "difficulty": "easy",
        "sow_indoors": [2, 3],
        "sow_outdoors": [4, 5],
        "transplant": [4, 5, 9],
        "harvest": [],
        "prune": [7, 8],
        "prune_notes": "Cut back hard after flowering to encourage fresh growth and second flush.",
        "watering": "low",
        "sunlight": "partial_shade",
        "soil": "any well-drained",
        "spacing_cm": 45,
        "height_cm": 40,
        "frost_tender": False,
        "companions": ["rose", "allium"],
        "avoid": [],
        "pests": ["sawfly"],
        "tips": "One of the most reliable, low-maintenance perennials for UK gardens.",
    },
    {
        "id": "allium",
        "common_name": "Ornamental Allium",
        "latin_name": "Allium hollandicum",
        "category": "bulb",
        "emoji": "💜",
        "description": "Architectural purple globes. Excellent for late spring interest.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [9, 10, 11],
        "transplant": [],
        "harvest": [],
        "prune": [7, 8],
        "prune_notes": "Leave seed heads for structural interest. Cut back when fully dry.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained",
        "spacing_cm": 15,
        "height_cm": 80,
        "frost_tender": False,
        "companions": ["rose", "geranium"],
        "avoid": [],
        "pests": [],
        "tips": "Plant bulbs 3× their own depth in autumn.",
    },
    {
        "id": "tulip",
        "common_name": "Tulip",
        "latin_name": "Tulipa",
        "category": "bulb",
        "emoji": "🌷",
        "description": "Spring-flowering bulb. Plant in November for best results in UK.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [10, 11],
        "transplant": [],
        "harvest": [],
        "prune": [5, 6],
        "prune_notes": "Deadhead after flowering. Allow leaves to die back naturally (6 weeks).",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained",
        "spacing_cm": 10,
        "height_cm": 50,
        "frost_tender": False,
        "companions": ["forget_me_not", "wallflower"],
        "avoid": [],
        "pests": ["tulip_fire", "squirrels"],
        "tips": "Plant late (November) to reduce risk of tulip fire disease.",
    },
    {
        "id": "daffodil",
        "common_name": "Daffodil",
        "latin_name": "Narcissus",
        "category": "bulb",
        "emoji": "🌼",
        "description": "British spring icon. Naturalises well in grass.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [9, 10, 11],
        "transplant": [],
        "harvest": [],
        "prune": [5],
        "prune_notes": "Allow leaves to die back naturally for 6 weeks after flowering. Tie in a knot if space is tight.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained",
        "spacing_cm": 10,
        "height_cm": 40,
        "frost_tender": False,
        "companions": [],
        "avoid": [],
        "pests": ["narcissus_bulb_fly", "basal_rot"],
        "tips": "Plant at 3× bulb depth. Deer and rabbit resistant.",
    },
    {
        "id": "snowdrop",
        "common_name": "Snowdrop",
        "latin_name": "Galanthus nivalis",
        "category": "bulb",
        "emoji": "🤍",
        "description": "First sign of spring. Best planted 'in the green' after flowering.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [2, 3, 9, 10],
        "transplant": [],
        "harvest": [],
        "prune": [],
        "prune_notes": "No pruning needed. Allow leaves to die down naturally.",
        "watering": "low",
        "sunlight": "partial_shade",
        "soil": "humus-rich, moisture-retentive",
        "spacing_cm": 8,
        "height_cm": 15,
        "frost_tender": False,
        "companions": ["hellebore", "cyclamen"],
        "avoid": [],
        "pests": [],
        "tips": "Plant 'in the green' (while still in leaf) for best establishment.",
    },
    {
        "id": "rhubarb",
        "common_name": "Rhubarb",
        "latin_name": "Rheum × hybridum",
        "category": "vegetable",
        "emoji": "🫚",
        "description": "Vigorous perennial. Leave for 2 years before harvesting.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [3, 4, 10, 11],
        "transplant": [],
        "harvest": [4, 5, 6],
        "prune": [10, 11],
        "prune_notes": "Remove any flower stalks immediately. Cut back dying foliage in autumn.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "deep, fertile",
        "spacing_cm": 90,
        "height_cm": 90,
        "frost_tender": False,
        "companions": [],
        "avoid": [],
        "pests": ["crown_rot", "slugs"],
        "tips": "Force for earlier, sweeter stems by covering with a terracotta pot in February.",
    },
    {
        "id": "asparagus",
        "common_name": "Asparagus",
        "latin_name": "Asparagus officinalis",
        "category": "vegetable",
        "emoji": "🌿",
        "description": "Perennial luxury veg. Patience required — don't harvest for 2 years.",
        "difficulty": "hard",
        "sow_indoors": [],
        "sow_outdoors": [3, 4],
        "transplant": [],
        "harvest": [4, 5, 6],
        "prune": [10, 11],
        "prune_notes": "Cut fern to 5 cm in autumn after it yellows. Don't cut before this.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "sandy, well-drained, fertile",
        "spacing_cm": 30,
        "height_cm": 150,
        "frost_tender": False,
        "companions": ["tomato", "basil", "parsley"],
        "avoid": [],
        "pests": ["asparagus_beetle", "slugs"],
        "tips": "Plant crowns (not seed) for earliest harvest. Bed lasts 20+ years.",
    },
    {
        "id": "gooseberry",
        "common_name": "Gooseberry",
        "latin_name": "Ribes uva-crispa",
        "category": "fruit",
        "emoji": "🍈",
        "description": "Traditional British soft fruit. Tolerates some shade.",
        "difficulty": "easy",
        "sow_indoors": [],
        "sow_outdoors": [11, 12, 1, 2, 3],
        "transplant": [],
        "harvest": [6, 7, 8],
        "prune": [12, 1, 2],
        "prune_notes": "Create open goblet shape. Remove crossing branches. Shorten sideshoots to 1–2 buds.",
        "watering": "moderate",
        "sunlight": "full_sun",
        "soil": "well-drained, fertile",
        "spacing_cm": 150,
        "height_cm": 120,
        "frost_tender": False,
        "companions": ["tomato"],
        "avoid": [],
        "pests": ["gooseberry_sawfly", "powdery_mildew", "birds"],
        "tips": "Net early to protect against birds. Sawfly can defoliate plants rapidly.",
    },
    {
        "id": "pear",
        "common_name": "Pear",
        "latin_name": "Pyrus communis",
        "category": "fruit",
        "emoji": "🍐",
        "description": "More cold-sensitive than apple. Espalier against a warm wall works well.",
        "difficulty": "moderate",
        "sow_indoors": [],
        "sow_outdoors": [11, 12, 1, 2, 3],
        "transplant": [],
        "harvest": [8, 9, 10],
        "prune": [12, 1, 2, 8],
        "prune_notes": "Similar to apple. Spur-prune side shoots. Pick pears slightly under-ripe and ripen indoors.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "deep, well-drained",
        "spacing_cm": 400,
        "height_cm": 350,
        "frost_tender": False,
        "companions": ["chive", "nasturtium"],
        "avoid": [],
        "pests": ["pear_scab", "pear_midge", "codling_moth"],
        "tips": "Plant 2 compatible varieties for cross-pollination.",
    },
    {
        "id": "thyme",
        "common_name": "Thyme",
        "latin_name": "Thymus vulgaris",
        "category": "herb",
        "emoji": "🌿",
        "description": "Compact aromatic herb. Excellent in containers and herb spirals.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [5],
        "transplant": [5, 6],
        "harvest": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "prune": [4, 5, 9],
        "prune_notes": "Trim after flowering to prevent woody leggy growth. Don't cut into old wood.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained, poor to moderate",
        "spacing_cm": 30,
        "height_cm": 25,
        "frost_tender": False,
        "companions": ["brassica", "strawberry", "tomato"],
        "avoid": [],
        "pests": [],
        "tips": "Replace every 3–4 years as plants become woody.",
    },
    {
        "id": "sage",
        "common_name": "Sage",
        "latin_name": "Salvia officinalis",
        "category": "herb",
        "emoji": "🌿",
        "description": "Aromatic evergreen subshrub. Culinary and ornamental uses.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [5],
        "transplant": [5, 6],
        "harvest": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "prune": [4, 5],
        "prune_notes": "Cut back lightly after flowering to maintain shape. Replace every 4–5 years.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained",
        "spacing_cm": 45,
        "height_cm": 50,
        "frost_tender": False,
        "companions": ["rosemary", "carrot", "brassica"],
        "avoid": ["basil", "cucumber"],
        "pests": ["froghoppers"],
        "tips": "Coloured sages (purple, golden) are equally aromatic and more ornamental.",
    },
    {
        "id": "parsley",
        "common_name": "Parsley",
        "latin_name": "Petroselinum crispum",
        "category": "herb",
        "emoji": "🌿",
        "description": "Biennial grown as annual. Needs warmth to germinate well.",
        "difficulty": "moderate",
        "sow_indoors": [3, 4],
        "sow_outdoors": [4, 5, 6, 7],
        "transplant": [5, 6],
        "harvest": [5, 6, 7, 8, 9, 10, 11],
        "prune": [],
        "prune_notes": "Harvest outer stems regularly. Remove flower stalks to prolong leaf production.",
        "watering": "moderate",
        "sunlight": "partial_shade",
        "soil": "fertile, well-drained",
        "spacing_cm": 20,
        "height_cm": 40,
        "frost_tender": False,
        "companions": ["tomato", "asparagus", "rose"],
        "avoid": [],
        "pests": ["celery_fly", "carrot_fly"],
        "tips": "Soak seeds overnight to speed up slow germination. Sow in situ as dislikes transplanting.",
    },
    {
        "id": "fennel",
        "common_name": "Fennel",
        "latin_name": "Foeniculum vulgare",
        "category": "herb",
        "emoji": "🌿",
        "description": "Tall anise-flavoured perennial. Attracts beneficial insects.",
        "difficulty": "easy",
        "sow_indoors": [3, 4],
        "sow_outdoors": [4, 5, 6],
        "transplant": [5],
        "harvest": [6, 7, 8, 9],
        "prune": [10],
        "prune_notes": "Cut to ground in autumn. Bronze fennel can be divided in spring.",
        "watering": "low",
        "sunlight": "full_sun",
        "soil": "well-drained",
        "spacing_cm": 45,
        "height_cm": 180,
        "frost_tender": False,
        "companions": ["dill"],
        "avoid": ["tomato", "bean", "courgette"],
        "pests": [],
        "tips": "Keep away from most vegetables — inhibits growth of many species.",
    },
]

PLANT_INDEX = {p["id"]: p for p in PLANTS}

SEASONAL_TASKS = {
    1: [
        "Order seeds from catalogues",
        "Plan crop rotations and new beds",
        "Check stored tubers and bulbs for rot",
        "Prune apple and pear trees on dry days",
        "Force rhubarb under pots",
        "Clean and sharpen tools",
    ],
    2: [
        "Sow onions, leeks, and broad beans indoors",
        "Chit seed potatoes in cool light",
        "Cut back autumn-fruiting raspberries",
        "Prune wisteria (second prune to 2–3 buds)",
        "Feed overwintering plants with general fertiliser",
        "Mulch borders as soil warms",
    ],
    3: [
        "Sow tomatoes, peppers, aubergines indoors",
        "Plant shallot and onion sets",
        "Sow carrots, parsnips direct",
        "Prune roses and shrubs",
        "Start hardening off early sowings",
        "Apply organic matter to vegetable beds",
    ],
    4: [
        "Sow beans, courgettes, cucumbers indoors",
        "Plant asparagus crowns",
        "Sow lettuce, spinach, peas outside",
        "Transplant brassica seedlings",
        "Watch out for last frosts — protect tender plants",
        "Begin regular slug and snail patrols",
    ],
    5: [
        "Plant out tomatoes, courgettes after last frost",
        "Sow sweetcorn, French and runner beans outside",
        "Thin seedlings as needed",
        "Plant up hanging baskets (keep under cover until June)",
        "Tie in climbing plants",
        "Water regularly in dry spells",
    ],
    6: [
        "Pinch out tomato side shoots",
        "Harvest broad beans, early peas, strawberries",
        "Earth up potatoes",
        "Deadhead flowers regularly",
        "Sow French beans successionally",
        "Begin feeding containers weekly",
    ],
    7: [
        "Harvest beans, courgettes, tomatoes regularly",
        "Prune stone fruit (plums, cherries) — never in winter",
        "Summer-prune wisteria (to 5 leaves)",
        "Mow wildflower areas after seeding",
        "Collect and dry herb seeds",
        "Water deeply every 3–4 days rather than lightly daily",
    ],
    8: [
        "Harvest main-crop tomatoes and sweetcorn",
        "Cut back summer-fruiting raspberry canes",
        "Sow green manures on empty beds",
        "Take cuttings of tender perennials",
        "Plant autumn-flowering bulbs (colchicum, crocus)",
        "Order spring bulbs for arrival in September",
    ],
    9: [
        "Plant spring bulbs: daffodils, alliums, snowdrops 'in the green'",
        "Harvest winter squash and pumpkins",
        "Divide herbaceous perennials",
        "Plant out spring brassicas",
        "Collect seeds from flowers and vegetables",
        "Begin composting spent crops",
    ],
    10: [
        "Plant garlic and overwintering onion sets",
        "Lift and store dahlias after first frost",
        "Clear vegetable beds and add compost",
        "Plant bare-root trees and hedging (from late Oct)",
        "Plant tulip bulbs (late October for disease avoidance)",
        "Net brassicas against pigeons",
    ],
    11: [
        "Plant bare-root roses and fruit trees",
        "Protect tender plants with fleece or bring inside",
        "Dig up and compost annual crops",
        "Prune apple and pear trees (open structure)",
        "Check stakes and ties on trees",
        "Cover brassicas for protection from hard frost",
    ],
    12: [
        "Plan next year's garden layout",
        "Continue pruning apples and pears in dry weather",
        "Insulate outdoor taps and pipes",
        "Clean pots and greenhouse glass",
        "Check stored crops — remove any rotting items",
        "Sharpen and oil tools before storage",
    ],
}


def get_region_for_postcode(postcode: str) -> str:
    postcode = postcode.upper().strip()
    for length in (3, 2, 1):
        prefix = postcode[:length]
        if prefix in POSTCODE_TO_REGION:
            return POSTCODE_TO_REGION[prefix]
    return "midlands"


def get_frost_dates(postcode: str) -> dict:
    region_key = get_region_for_postcode(postcode)
    region = UK_REGIONS[region_key]
    start = region["frost_free_start"]
    end = region["frost_free_end"]
    return {
        "region": region["name"],
        "region_key": region_key,
        "frost_free_start": f"{MONTHS[start[0]-1]} {start[1]}",
        "frost_free_end": f"{MONTHS[end[0]-1]} {end[1]}",
        "frost_free_start_month": start[0],
        "frost_free_end_month": end[0],
    }


def get_current_tasks(month: int = None) -> list:
    if month is None:
        month = date.today().month
    return SEASONAL_TASKS.get(month, [])


def get_plants_to_sow_now(month: int = None) -> list:
    if month is None:
        month = date.today().month
    results = []
    for plant in PLANTS:
        if month in plant["sow_indoors"]:
            results.append({"plant": plant, "action": "sow_indoors"})
        elif month in plant["sow_outdoors"]:
            results.append({"plant": plant, "action": "sow_outdoors"})
    return results


def get_plants_to_prune_now(month: int = None) -> list:
    if month is None:
        month = date.today().month
    return [p for p in PLANTS if month in p["prune"]]


def get_plants_to_harvest_now(month: int = None) -> list:
    if month is None:
        month = date.today().month
    return [p for p in PLANTS if month in p["harvest"]]


def search_plants(query: str) -> list:
    q = query.lower()
    return [
        p for p in PLANTS
        if q in p["common_name"].lower() or q in p["latin_name"].lower()
        or q in p["category"] or q in " ".join(p["pests"])
    ]


def get_plant(plant_id: str) -> dict | None:
    return PLANT_INDEX.get(plant_id)


def get_companion_info(plant_id: str) -> dict:
    plant = PLANT_INDEX.get(plant_id)
    if not plant:
        return {}
    return {
        "plant": plant["common_name"],
        "good_companions": [PLANT_INDEX[c]["common_name"] for c in plant["companions"] if c in PLANT_INDEX],
        "avoid": plant["avoid"],
    }
